spring:
  application:
    name: library
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/library
    username: library-user
    password: libraryPassword
  liquibase:
    change-log: classpath:/db/changelog.xml
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
